#!/bin/bash
# /usr/local/bin/netconf
# Author: backenfutter
#
# Credits : grenouille
# 
# INSTALLATION
# ============
# Requires wpa_supplicant and encfs to be installed. Paste this to your terminal:
# sudo aptitude install wpa_supplicant encfs
#
#
# This script requires a wpa_supplicant configuration file named c-base.conf
# in an encfs folder /etc/wpa_supplicant/c-base/ 
# 
# Paste this to your terminal to set it up as required:
# sudo encfs /etc/wpa_supplicant/.c-base /etc/wpa_supplicant/c-base && vi /etc/wpa_supplicant/c-base/c-base.conf
#
# Example c-base.conf at http://wiki.c-base.org/coredump/wlan-c-base-crew
#

export LC_ALL=C

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

function reset_interface {
	echo "Reseting interfaces..."
	killall wvdial &> /dev/null
	killall dhclient  &> /dev/null
	killall wpa_supplicant &> /dev/null
	ifconfig eth0 down
	ifconfig wlan0 down
	modprobe -r iwlagn      # These two lines eventually need to be
	modprobe iwlagn         # set to _your_ WLAN kernel module name
	sleep 1
	cat /dev/null > /etc/resolv.conf
}

function test_connectivity {
	if ping -c 1 google.de &> /dev/null ; then
		echo "[$1] Verbindungsaufbau abgeschlossen"
	else
		echo "Probleme beim Verbindungsaufbau..."
	fi
}

case "$1" in
1|lan)                          # c-base crewlan
        reset_interface
        ifconfig eth0 up
        dhclient eth0
        test_connectivity "lan"
		;;

2|c-base)                       # c-base wlan => cbase1
        reset_interface
        ifconfig wlan0 up
        sleep 3
        iwconfig wlan0 essid cbase1
        dhclient wlan0
        test_connectivity "cbase1"
        ;;

3|c-base-crew)                  # cbase crew-wlan wpa-eap 
        reset_interface
        ifconfig wlan0 up
        if [ `mount|grep -o /etc/wpa_supplicant/c-base` ] ; then
             echo  "> enfs already mounted"
        else
               encfs -i 1 /etc/wpa_supplicant/.c-base /etc/wpa_supplicant/c-base
        fi 
        sleep 1
        wpa_supplicant  -B -i wlan0 -c/etc/wpa_supplicant/c-base/c-base.conf
        #wpa_supplicant  -ddd -i wlan0 -c/etc/wpa_supplicant/c-base/c-base.conf
        sleep 3
        iwconfig 
        fusermount -u /etc/wpa_supplicant/c-base/ 
        dhclient wlan0
        test_connectivity "c-base-crew"
        ;;

r|reset)                                # reset the interfaces => »go offline«
        reset_interface
        ;;

params)
        echo `grep \) $0 | grep -v grep | grep -v '*'|grep -v 'params)'| sed s/\)// |sed s/\#.*//| sed s/\|/\ /g`
        ;;

*)
        grep "#" $0 | grep -v ")" | grep -v "supplicant"
        echo "usage: `basename $0` OPTION"
        echo "OPTIONS:"
        echo "================================="
        grep \) $0 | grep -v grep | grep -v '*'|grep -v 'params)'|sed s/\)//  
        echo
        exit 1
        ;;
esac

exit 0

